version: "3.8"

services:
  demo-grpc:
    build:
      dockerfile: Dockerfile.jvm
    ports:
      - "8080:8080"
      - "9000:9000"
      - "1099:1099"
    mem_limit: 400m

  mongo:
    image: mongo
    mem_limit: 300m
    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: gameofthrones
      retryWrites: false
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    mem_limit: 300m
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
